"""Generate a simple index for report outputs under src/reports."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_REPORTS_ROOT = ROOT / "src" / "reports"
DEFAULT_OUTPUT_PATH = DEFAULT_REPORTS_ROOT / "INDEX.md"
REPORT_EXTENSIONS = {".md", ".csv", ".json"}


@dataclass
class ReportGroup:
    name: str
    relative_dir: str
    files: List[Path]


def _collect_report_groups(reports_root: Path) -> List[ReportGroup]:
    groups: List[ReportGroup] = []
    for directory in sorted(path for path in reports_root.rglob("*") if path.is_dir()):
        files = sorted(
            file_path
            for file_path in directory.iterdir()
            if file_path.is_file() and file_path.suffix in REPORT_EXTENSIONS
        )
        if not files:
            continue
        relative_dir = str(directory.relative_to(reports_root))
        groups.append(ReportGroup(name=directory.name, relative_dir=relative_dir, files=files))
    return groups


def _latest_files_by_extension(files: List[Path]) -> Dict[str, str]:
    latest: Dict[str, str] = {}
    for extension in sorted(REPORT_EXTENSIONS):
        matching = [file_path for file_path in files if file_path.suffix == extension]
        if not matching:
            continue
        latest_file = max(matching, key=lambda file_path: file_path.name)
        latest[extension] = latest_file.name
    return latest


def render_index(reports_root: Path) -> str:
    """Return markdown content listing report groups and latest files."""
    groups = _collect_report_groups(reports_root)
    lines: List[str] = []
    lines.append("# Reports Index")
    lines.append("")
    lines.append("Generated by `src/kalshi/build_reports_index.py`.")
    lines.append("")
    lines.append("## How To Use")
    lines.append("")
    lines.append("- Start with this file to locate the latest output for each workflow.")
    lines.append("- Prefer files under `baselines/` and `experiments/` for active analysis.")
    lines.append("- Treat `archive/` as historical context, not active signal.")
    lines.append("")
    lines.append("## Groups")
    lines.append("")

    if not groups:
        lines.append("No reports found.")
        return "\n".join(lines) + "\n"

    for group in groups:
        latest = _latest_files_by_extension(group.files)
        lines.append(f"### `{group.relative_dir}`")
        lines.append("")
        lines.append(f"- Total files: `{len(group.files)}`")
        for extension in (".md", ".csv", ".json"):
            if extension in latest:
                lines.append(f"- Latest {extension}: `{latest[extension]}`")
        lines.append("- Files:")
        for file_path in group.files:
            rel = file_path.relative_to(reports_root)
            lines.append(f"  - `{rel}`")
        lines.append("")
    return "\n".join(lines)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build src/reports/INDEX.md for easier report discovery.")
    parser.add_argument("--reports-root", type=Path, default=DEFAULT_REPORTS_ROOT, help="Root reports directory")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH, help="Output markdown path")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    index_markdown = render_index(args.reports_root)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(index_markdown)
    print(f"Wrote report index: {args.output}")


if __name__ == "__main__":
    main()
